name: deploy-book
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./julia-intro

    steps:
    - uses: actions/checkout@v4
    # Install dependencies
    - name: Set up MiniConda
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.3.1-0'
        environment-file: ./julia-intro/environment.yml
      init-shell: bash powershell

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./julia-intro/_build/html
